const PERMISSIONS = {
  // Masters
  MASTERS_READ: 'masters:read',
  MASTERS_WRITE: 'masters:write',
  MASTERS_DELETE: 'masters:delete',
  // Finance
  FINANCE_READ: 'finance:read',
  FINANCE_WRITE: 'finance:write',
  FINANCE_DELETE: 'finance:delete',
  FINANCE_APPROVE: 'finance:approve',
  // Sales
  SALES_READ: 'sales:read',
  SALES_WRITE: 'sales:write',
  SALES_DELETE: 'sales:delete',
  // Purchase
  PURCHASE_READ: 'purchase:read',
  PURCHASE_WRITE: 'purchase:write',
  PURCHASE_DELETE: 'purchase:delete',
  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  // Imports
  IMPORTS_READ: 'imports:read',
  IMPORTS_WRITE: 'imports:write',
  // HR
  HR_READ: 'hr:read',
  HR_WRITE: 'hr:write',
  HR_APPROVE: 'hr:approve',
  // Reports
  REPORTS_READ: 'reports:read',
  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  // Users
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',
  // Approvals
  APPROVALS_MANAGE: 'approvals:manage',
  // Admin
  ADMIN: 'admin',
};

const ROLE_PERMISSIONS = {
  role_superadmin: Object.values(PERMISSIONS),
  role_owner: [
    PERMISSIONS.MASTERS_READ, PERMISSIONS.FINANCE_READ, PERMISSIONS.SALES_READ,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.INVENTORY_READ, PERMISSIONS.IMPORTS_READ,
    PERMISSIONS.HR_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.SETTINGS_READ, PERMISSIONS.USERS_READ,
  ],
  role_gm: [
    PERMISSIONS.MASTERS_READ, PERMISSIONS.MASTERS_WRITE,
    PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_WRITE, PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_WRITE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_WRITE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.IMPORTS_READ, PERMISSIONS.IMPORTS_WRITE,
    PERMISSIONS.HR_READ, PERMISSIONS.HR_WRITE, PERMISSIONS.HR_APPROVE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.USERS_READ, PERMISSIONS.APPROVALS_MANAGE,
  ],
  role_accountant: [
    PERMISSIONS.MASTERS_READ, PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.SALES_READ, PERMISSIONS.PURCHASE_READ, PERMISSIONS.REPORTS_READ,
  ],
  role_branch_mgr: [
    PERMISSIONS.MASTERS_READ, PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_WRITE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_WRITE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.HR_READ, PERMISSIONS.REPORTS_READ,
  ],
  role_manager: [
    PERMISSIONS.MASTERS_READ, PERMISSIONS.IMPORTS_READ, PERMISSIONS.IMPORTS_WRITE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.REPORTS_READ,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
